# slurm.conf
ClusterName=docker
ControlMachine=slurm-master


AuthType=auth/munge
CryptoType=crypto/munge

SlurmUser=slurm
# Update these paths according to your Dockerfile's defined locations
StateSaveLocation=/var/spool/slurm/ctld
SlurmdSpoolDir=/var/spool/slurm/d
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log

# Communication settings
SlurmctldPort=6817
SlurmdPort=6818
SwitchType=switch/none
MpiDefault=none
ProctrackType=proctrack/linuxproc

# Define the nodes
NodeName=slurm-worker1 NodeAddr=slurm-worker1 CPUs=10 State=UNKNOWN
NodeName=slurm-worker2 NodeAddr=slurm-worker2 CPUs=10 State=UNKNOWN

# Define a partition
PartitionName=debug Nodes=slurm-worker1,slurm-worker2 Default=YES MaxTime=INFINITE State=UP
