

#include <stdlib.h>
#include <stdio.h> 


#define XWIDTH 1000
#define YWIDTH 1000
#define COLOR_DEPTH 255

// =============================================================
//  utilities for managing ppm files
//
//  * write_pgm_image
// =============================================================

void write_ppm_image( void *image, int xsize, int ysize, const char *image_name)
/*
 * image        : a pointer to the memory region that contains the image
 * xsize, ysize : x and y dimensions of the image
 * image_name   : the name of the file to be written
 *
 * we assume 255 as maximum value per channel
 */
{
  FILE* image_file; 
  image_file = fopen(image_name, "w"); 
  
  // Writing header
  // The header's format is as follows, all in ASCII.
  // "whitespace" is either a blank or a TAB or a CF or a LF
  // - The Magic Number (see below the magic numbers)
  // - the image's width
  // - the height
  // - a white space
  // - the image's height
  // - a whitespace
  // - the maximum color value, which must be between 0 and 65535
  //
  
  fprintf(image_file, "P6\n# generated by\n# put here your name\n%d %d\n%d\n", xsize, ysize, COLOR_DEPTH);
  
  // Writing file
  fwrite( image, 3, xsize*ysize, image_file);  

  fclose(image_file); 
  return ;

  /* ---------------------------------------------------------------

     TYPE    MAGIC NUM     EXTENSION   COLOR RANGE
           ASCII  BINARY

     PBM   P1     P4       .pbm        [0-1]
     PGM   P2     P5       .pgm        [0-255] or [0-2^16[
     PPM   P3     P6       .ppm        [0-2^24[
  
  ------------------------------------------------------------------ */
}



// =============================================================
//

void * generate_gradient( const int channel, const int xsize, const int ysize )
/*
 * just and example about how to generate a vertical gradient
 * channel : 0 | 1 | 2  (red, green, blue)
 * x and y : dimensions of the image to be generated.
 *
 * The memory region that will contain the image is returned
 * by the function as a void *
 *
 */
{
  typedef unsigned char pixel_t[3];
  pixel_t *image;

  unsigned char maxval = COLOR_DEPTH;
  unsigned char minval = 0; 
  unsigned char delta  = (unsigned char)((double)(maxval - minval) / ysize);
  if(delta < 1 )
    delta = 1;

  image = (pixel_t*)calloc( xsize*ysize, sizeof(pixel_t) );
  if ( image == NULL )
    return NULL;
  
  int idx = 0;
  for ( int yy = 0; yy < ysize; yy++ )
    {
      unsigned char value = minval + (char)(yy*delta);
      for( int xx = 0; xx < xsize; xx++ )
	image[idx++][channel] = (value > maxval)?maxval:value;
    }

  return (void*)image;
}




int main( int argc, char **argv ) 
{ 
    int xsize      = XWIDTH;
    int ysize      = YWIDTH;
   
    if ( argc > 1 )
      {
	xsize = atoi( *(argv+1) );
	ysize = atoi( *(argv+1) );
      }

    // ---------------------------------------------------
    //
    // generate red gradient
    void *ptr = generate_gradient( 0, xsize, ysize );
    if ( ptr == NULL ) {
      printf("it was impossible to allocate the memory to host the image\n");
      return 1; }      
    
    printf("The red gradient has been generated\n");
    write_ppm_image( ptr, xsize, ysize, "red_image.ppm" );
    printf("The gradient has been written\n");

    free(ptr);

    // ---------------------------------------------------
    //
    // generate green gradient
    ptr = generate_gradient( 1, xsize, ysize );
    if ( ptr == NULL ) {
      printf("it was impossible to allocate the memory to host the image\n");
      return 2; }
    
    printf("The green gradient has been generated\n");
    write_ppm_image( ptr, xsize, ysize, "green_image.ppm" );
    printf("The gradient has been written\n");

    free(ptr);

    // ---------------------------------------------------
    //
    // generate blue gradient
    ptr = generate_gradient( 2, xsize, ysize );
    if ( ptr == NULL ) {
      printf("it was impossible to allocate the memory to host the image\n");
      return 2; }

    printf("The blue gradient has been generated\n");
    write_ppm_image( ptr, xsize, ysize, "blue_image.ppm" );
    printf("The gradient has been written\n");

    free(ptr);

    return 0;
} 



